fix

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,33 +1,238 @@
-# # image: https://registry.hub.docker.com/r/frappe/erpnext-worker
-# # docs: https://github.com/frappe/frappe_docker/blob/main/pwd.yml
+# version: "3"
 
-version: "3.8"
+# services:
+#   backend:
+#     image: frappe/erpnext:latest
+#     deploy:
+#       restart_policy:
+#         condition: on-failure
+#     volumes:
+#       - ./sites:/home/frappe/frappe-bench/sites
+#       - ./logs:/home/frappe/frappe-bench/logs
+
+#   configurator:
+#     image: frappe/erpnext:latest
+#     deploy:
+#       restart_policy:
+#         condition: none
+#     entrypoint:
+#       - bash
+#       - -c
+#     command:
+#       - >
+#         ls -1 apps > sites/apps.txt;
+#         bench set-config -g db_host $$DB_HOST;
+#         bench set-config -gp db_port $$DB_PORT;
+#         bench set-config -g redis_cache "redis://$$REDIS_CACHE";
+#         bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
+#         bench set-config -g redis_socketio "redis://$$REDIS_SOCKETIO";
+#         bench set-config -gp socketio_port $$SOCKETIO_PORT;
+#     environment:
+#       DB_HOST: db
+#       DB_PORT: "3306"
+#       REDIS_CACHE: redis-cache:6379
+#       REDIS_QUEUE: redis-queue:6379
+#       REDIS_SOCKETIO: redis-socketio:6379
+#       SOCKETIO_PORT: "9000"
+#     volumes:
+#       - ./sites:/home/frappe/frappe-bench/sites
+#       - ./logs:/home/frappe/frappe-bench/logs
+
+#   create-site:
+#     image: frappe/erpnext:latest
+#     deploy:
+#       restart_policy:
+#         condition: none
+#     volumes:
+#       - ./sites:/home/frappe/frappe-bench/sites
+#       - ./logs:/home/frappe/frappe-bench/logs
+#     entrypoint:
+#       - bash
+#       - -c
+#     command:
+#       - >
+#         wait-for-it -t 120 db:3306;
+#         wait-for-it -t 120 redis-cache:6379;
+#         wait-for-it -t 120 redis-queue:6379;
+#         wait-for-it -t 120 redis-socketio:6379;
+#         export start=`date +%s`;
+#         until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
+#           [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
+#           [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
+#         do
+#           echo "Waiting for sites/common_site_config.json to be created";
+#           sleep 5;
+#           if (( `date +%s`-start > 120 )); then
+#             echo "could not find sites/common_site_config.json with required keys";
+#             exit 1
+#           fi
+#         done;
+#         echo "sites/common_site_config.json found";
+#         bench new-site frontend --no-mariadb-socket --admin-password=admin --db-root-password=admin --install-app erpnext --set-default;
+
+#   db:
+#     image: mariadb:10.6
+#     healthcheck:
+#       test: mysqladmin ping -h localhost --password=admin
+#       interval: 1s
+#       retries: 15
+#     deploy:
+#       restart_policy:
+#         condition: on-failure
+#     command:
+#       - --character-set-server=utf8mb4
+#       - --collation-server=utf8mb4_unicode_ci
+#       - --skip-character-set-client-handshake
+#       - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
+#     environment:
+#       MYSQL_ROOT_PASSWORD: admin
+#     volumes:
+#       - ./db-data:/var/lib/mysql
+
+#   frontend:
+#     image: frappe/erpnext:latest
+#     deploy:
+#       restart_policy:
+#         condition: on-failure
+#     command:
+#       - nginx-entrypoint.sh
+#     environment:
+#       BACKEND: backend:8000
+#       FRAPPE_SITE_NAME_HEADER: frontend
+#       SOCKETIO: websocket:9000
+#       UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
+#       UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
+#       UPSTREAM_REAL_IP_RECURSIVE: "off"
+#       PROXY_READ_TIMOUT: 120
+#       CLIENT_MAX_BODY_SIZE: 50m
+#       ADMIN_PASSWORD: $ADMIN_PASSWORD
+#     volumes:
+#       - ./sites:/home/frappe/frappe-bench/sites
+#       - ./logs:/home/frappe/frappe-bench/logs
+#     ports:
+#       - "172.17.0.1:8989:8080"
+
+#   queue-default:
+#     image: frappe/erpnext:latest
+#     deploy:
+#       restart_policy:
+#         condition: on-failure
+#     command:
+#       - bench
+#       - worker
+#       - --queue
+#       - default
+#     volumes:
+#       - ./sites:/home/frappe/frappe-bench/sites
+#       - ./logs:/home/frappe/frappe-bench/logs
+
+#   queue-long:
+#     image: frappe/erpnext:latest
+#     deploy:
+#       restart_policy:
+#         condition: on-failure
+#     command:
+#       - bench
+#       - worker
+#       - --queue
+#       - long
+#     volumes:
+#       - ./sites:/home/frappe/frappe-bench/sites
+#       - ./logs:/home/frappe/frappe-bench/logs
+
+#   queue-short:
+#     image: frappe/erpnext:latest
+#     deploy:
+#       restart_policy:
+#         condition: on-failure
+#     command:
+#       - bench
+#       - worker
+#       - --queue
+#       - short
+#     volumes:
+#       - ./sites:/home/frappe/frappe-bench/sites
+#       - ./logs:/home/frappe/frappe-bench/logs
+
+#   redis-queue:
+#     image: redis:6.2-alpine
+#     deploy:
+#       restart_policy:
+#         condition: on-failure
+#     volumes:
+#       - ./redis-queue-data:/data
+
+#   redis-cache:
+#     image: redis:6.2-alpine
+#     deploy:
+#       restart_policy:
+#         condition: on-failure
+#     volumes:
+#       - ./redis-cache-data:/data
+
+#   redis-socketio:
+#     image: redis:6.2-alpine
+#     deploy:
+#       restart_policy:
+#         condition: on-failure
+#     volumes:
+#       - ./redis-socketio-data:/data
+
+#   scheduler:
+#     image: frappe/erpnext:latest
+#     deploy:
+#       restart_policy:
+#         condition: on-failure
+#     command:
+#       - bench
+#       - schedule
+#     volumes:
+#       - ./sites:/home/frappe/frappe-bench/sites
+#       - ./logs:/home/frappe/frappe-bench/logs
+
+#   websocket:
+#     image: frappe/erpnext:latest
+#     deploy:
+#       restart_policy:
+#         condition: on-failure
+#     command:
+#       - node
+#       - /home/frappe/frappe-bench/apps/frappe/socketio.js
+#     volumes:
+#       - ./sites:/home/frappe/frappe-bench/sites
+#       - ./logs:/home/frappe/frappe-bench/logs
+
+version: "3"
 
 services:
   backend:
-    image: frappe/erpnext-worker:${APP_VERSION}
-    restart: always
+    image: frappe/erpnext-worker:v14.9.0
+    deploy:
+      restart_policy:
+        condition: on-failure
     volumes:
       - sites:/home/frappe/frappe-bench/sites
       - assets:/home/frappe/frappe-bench/sites/assets
 
   configurator:
-    image: frappe/erpnext-worker:${APP_VERSION}
+    image: frappe/erpnext-worker:v14.9.0
     command:
       - configure.py
     environment:
       DB_HOST: db
       DB_PORT: "3306"
-      REDIS_CACHE: redis:6379/0
-      REDIS_QUEUE: redis:6379/1
-      REDIS_SOCKETIO: redis:6379/2
+      REDIS_CACHE: redis-cache:6379
+      REDIS_QUEUE: redis-queue:6379
+      REDIS_SOCKETIO: redis-socketio:6379
       SOCKETIO_PORT: "9000"
     volumes:
       - sites:/home/frappe/frappe-bench/sites
 
   create-site:
-    image: frappe/erpnext-worker:${APP_VERSION}
-    restart: always
+    image: frappe/erpnext-worker:v14.9.0
+    deploy:
+      restart_policy:
+        condition: on-failure
     volumes:
       - sites:/home/frappe/frappe-bench/sites
       - assets:/home/frappe/frappe-bench/sites/assets
@@ -36,8 +241,10 @@ services:
       - -c
     command:
       - >
-        wait-for-it -t 20 db:3306;
-        wait-for-it -t 20 redis:6379;
+        wait-for-it -t 120 db:3306;
+        wait-for-it -t 120 redis-cache:6379;
+        wait-for-it -t 120 redis-queue:6379;
+        wait-for-it -t 120 redis-socketio:6379;
         export start=`date +%s`;
         until [[ -n `grep -hs ^ common_site_config.json | jq -r ".db_host // empty"` ]] && \
           [[ -n `grep -hs ^ common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
@@ -45,21 +252,22 @@ services:
         do
           echo "Waiting for common_site_config.json to be created";
           sleep 5;
-          if (( `date +%s`-start > 20 )); then
+          if (( `date +%s`-start > 120 )); then
             echo "could not find common_site_config.json with required keys";
             exit 1
           fi
         done;
         echo "common_site_config.json found";
-        bench new-site frontend --admin-password=${APP_PASSWORD} --${APP_DB_PARAM}-root-password=${DB_MARIA_PASSWORD} --install-app erpnext;
-
+        bench new-site frontend --admin-password=admin --db-root-password=admin --install-app payments --install-app erpnext --set-default;
   db:
     image: mariadb:10.6
     healthcheck:
       test: mysqladmin ping -h localhost --password=admin
       interval: 1s
       retries: 15
-    restart: always
+    deploy:
+      restart_policy:
+        condition: on-failure
     command:
       - --character-set-server=utf8mb4
       - --collation-server=utf8mb4_unicode_ci
@@ -69,12 +277,17 @@ services:
       MYSQL_ROOT_PASSWORD: admin
     volumes:
       - db-data:/var/lib/mysql
-    ports:
-      - "${DB_MARIA_PORT}:3306"
-      
+
   frontend:
-    image: frappe/erpnext-nginx:${APP_VERSION}
-    restart: always
+    image: frappe/erpnext-nginx:v14.9.0
+    deploy:
+      restart_policy:
+        condition: on-failure
+    depends_on:
+      backend:
+        condition: service_started
+      websocket:
+        condition: service_started
     environment:
       BACKEND: backend:8000
       FRAPPE_SITE_NAME_HEADER: frontend
@@ -89,8 +302,10 @@ services:
       - "172.17.0.1:8989:8080"
 
   queue-default:
-    image: frappe/erpnext-worker:${APP_VERSION}
-    restart: always
+    image: frappe/erpnext-worker:v14.9.0
+    deploy:
+      restart_policy:
+        condition: on-failure
     command:
       - bench
       - worker
@@ -98,10 +313,13 @@ services:
       - default
     volumes:
       - sites:/home/frappe/frappe-bench/sites
+      - assets:/home/frappe/frappe-bench/sites/assets
 
   queue-long:
-    image: frappe/erpnext-worker:${APP_VERSION}
-    restart: always
+    image: frappe/erpnext-worker:v14.9.0
+    deploy:
+      restart_policy:
+        condition: on-failure
     command:
       - bench
       - worker
@@ -109,10 +327,13 @@ services:
       - long
     volumes:
       - sites:/home/frappe/frappe-bench/sites
+      - assets:/home/frappe/frappe-bench/sites/assets
 
   queue-short:
-    image: frappe/erpnext-worker:${APP_VERSION}
-    restart: always
+    image: frappe/erpnext-worker:v14.9.0
+    deploy:
+      restart_policy:
+        condition: on-failure
     command:
       - bench
       - worker
@@ -120,30 +341,57 @@ services:
       - short
     volumes:
       - sites:/home/frappe/frappe-bench/sites
+      - assets:/home/frappe/frappe-bench/sites/assets
 
-  redis:
+  redis-queue:
     image: redis:6.2-alpine
-    restart: always
+    deploy:
+      restart_policy:
+        condition: on-failure
     volumes:
-      - redis-data:/data
+      - redis-queue-data:/data
+
+  redis-cache:
+    image: redis:6.2-alpine
+    deploy:
+      restart_policy:
+        condition: on-failure
+    volumes:
+      - redis-cache-data:/data
+
+  redis-socketio:
+    image: redis:6.2-alpine
+    deploy:
+      restart_policy:
+        condition: on-failure
+    volumes:
+      - redis-socketio-data:/data
 
   scheduler:
-    image: frappe/erpnext-worker:${APP_VERSION}
-    restart: always
+    image: frappe/erpnext-worker:v14.9.0
+    deploy:
+      restart_policy:
+        condition: on-failure
     command:
       - bench
       - schedule
     volumes:
       - sites:/home/frappe/frappe-bench/sites
+      - assets:/home/frappe/frappe-bench/sites/assets
 
   websocket:
-    image: frappe/frappe-socketio:${APP_VERSION}
-    restart: always
+    image: frappe/frappe-socketio:v14.17.1
+    deploy:
+      restart_policy:
+        condition: on-failure
     volumes:
       - sites:/home/frappe/frappe-bench/sites
+      - assets:/home/frappe/frappe-bench/sites/assets
 
 volumes:
   assets:
   db-data:
-  redis-data:
+  redis-queue-data:
+  redis-cache-data:
+  redis-socketio-data:
   sites:
